rm(list = ls())
Data <- read.csv("~/Documents/DataAnalytics/DT-Credit.csv", header=TRUE, sep = ";")
str(Data)
cols <- c(1:2, 4:10, 12:22, 24:32)
Data[cols] <- lapply(Data[cols], factor)
str(Data)
Data <- Data[-1]
names(Data)
DT_Model <- rpart(RESPONSE~.,data=Data, control = rpart.control(minsplit=60,minbucket = 30,maxdepth = 4))
summary(DT_Model)
plot(as.party(DT_Model))
print(DT_Model)
DT_Model2 <- rpart(RESPONSE~., data=Data)
plot(as.party(DT_Model2))
print(DT_Model2$cptable)
opt <- which.min(DT_Model2$cptable[,"xerror"])
print(opt)
cp <- DT_Model2$cptable[opt,"CP"]
DT_Model_Pruned <- prune(DT_Model2, cp=cp)
plot(as.party(DT_Model_Pruned))
print(DT_Model_Pruned)
RF <- randomForest(RESPONSE~.,data=Data)
print(RF)
importance(RF)
varImpPlot(RF)
plot(RF)