rm(list=ls())
setwd("~/Documents/DataAnalytics/")
Data <- read.csv("HS.csv", header=TRUE, sep=",")
Data
str(Data)
attach(Data)
head(Data)
summary(Data)
Impute1 <- kNN(Data, variable = "Genre", k=5)
summary(Impute1)
Impute2 <- kNN(Data, variable = c("Audience..score..", "Profitability"), k=6)
summary(Impute2)
Impute3 <- kNN(Data, variable="Rotten.Tomatoes..", k=6)
summary(Impute3)